import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/header/Header' 
import Landing from '../components/landing/Landing'
import About from '../components/landing/About'

const Home: NextPage = () => {
  return (
    <div className = "w-full h-full">
      <Head>
        <title>Hemank Patwal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <Header/>
          <Landing/>
         
    </div>
  )
}

export default Home
